### ISSUE TITLE
Installing packages fails on fresh clone of repo

### ISSUE THREAD

**Issue by looeee** [LXSMNSYC/tailwind-layouts#1]
Steps to reproduce: 

1. git clone repo
2. `npm install`

Results in the following error:

```
npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: tailwind-layouts@0.0.0
npm ERR! Found: monaco-editor@0.24.0
npm ERR! node_modules/monaco-editor
npm ERR!   monaco-editor@"^0.24.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer monaco-editor@"^0.23.0" from @monaco-editor/react@4.1.3
npm ERR! node_modules/@monaco-editor/react
npm ERR!   @monaco-editor/react@"^4.1.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Lewy\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lewy\AppData\Local\npm-cache\_logs\2021-06-24T03_19_25_628Z-debug.log
```

OS: Windows

Workaround:

```
npm install --legacy-peer-deps
```

This seems to work, although in my experience usually this is a fragile workaround.

**Comment by lxsmnsyc** [comment]
Thanks for submitting this issue!

I have updated the dependencies (`@monaco-editor/react` has updated their version as well as `monaco-editor`) and have added a `package-lock.json` file since you have attempted to run this without yarn (the website was developed through yarn).

The error might be caused of the lack of `package-lock.json`.

Please try again and see if you can reproduce the issue, thank you!

Edit:
After researching, the error may also be caused of how NPM 7 automatically installs missing peer dependencies.

**Comment by looeee** [comment]
Just tested again, looks all good now :)
